#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

umask "${UMASK}"

export SHELL=/bin/bash
export DOTNET_EnableDiagnostics=0
export DOTNET_BUNDLE_EXTRACT_BASE_DIR="${CONFIG_DIR}/.net"
export DOTNET_gcServer=0
export DOTNET_gcConcurrent=1
export DOTNET_GCHeapHardLimit=0x80000000
export DOTNET_GCConserveMemory=9

readarray -td, PORTS <<< "${WEBUI_PORTS}"
HTTP_PORT=${PORTS[0]%%/*}
HTTPS_PORT=${PORTS[1]%%/*}

if [[ "${VPN_ENABLED}" == "true" ]] && [[ "${VPN_AUTO_PORT_FORWARD}" != "false" ]]; then
    log_inf "[SLSKD] Delaying start until forwarded port is available."
    until [[ -f "${CONFIG_DIR}/wireguard/forwarded_port_validated" ]]; do   
        sleep 1
    done
    forwarded_port=$(sed -n '1p' "${CONFIG_DIR}/wireguard/forwarded_port_validated")
    ARGS="--slsk-listen-port ${forwarded_port}"
    log_inf "[SLSKD] Starting with forwarded port [${forwarded_port}]."
fi

# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/slskd" --app-dir "${CONFIG_DIR}" --http-port "${HTTP_PORT}" --https-port "${HTTPS_PORT}" ${ARGS}
