#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

export SHELL=/bin/bash
export DOTNET_EnableDiagnostics=0
export DOTNET_BUNDLE_EXTRACT_BASE_DIR="${CONFIG_DIR}/.net"
export DOTNET_gcServer=0
export DOTNET_gcConcurrent=1
export DOTNET_GCHeapHardLimit=0x80000000
export DOTNET_GCConserveMemory=9

readarray -td, PORTS <<< "${WEBUI_PORTS}"
HTTP_PORT=${PORTS[0]%%/*}
HTTPS_PORT=${PORTS[1]%%/*}

if [[ "${VPN_ENABLED}" == "true" ]] && [[ "${VPN_AUTO_PORT_FORWARD}" != "false" ]] && yq -re '.soulseek.listen_port' "${CONFIG_DIR}/slskd.yml" 2> /dev/null; then
    until [[ -f "${CONFIG_DIR}/wireguard/forwarded_port_updated" ]]; do   
        sleep 1
    done
fi

# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/slskd" --app-dir "${CONFIG_DIR}" --http-port "${HTTP_PORT}" --https-port "${HTTPS_PORT}"
